version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/public:/var/www/app/public:delegated
      - ./frontend/dist:/var/www/app/public/dist:delegated